apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.videos.name }}-pv
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.videos.hostPath }} # Reemplaza con la ruta del directorio en tu máquina
