apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.videos.name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.volumes.videos.name }}-pv